# Generated by Django 4.1.1 on 2022-11-21 10:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textarea', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
